### ISSUE TITLE
MVP Memory Game

### ISSUE THREAD

**Issue by KoolTheba** [KoolTheba/memory-game#13]
### Features added
- [x] https://github.com/KoolTheba/memory-game/commit/104f507c8debe833d9f357f00e8d6348f18c87c6 Clone original repository
- [x] #8 Grid (Doc #3)
- [x] #9 Clicks functionality (Doc #4)
- [x] #11 Matching logic (Doc #5)
- [x] #12 Winning condition (Doc #6)
- [x] https://github.com/KoolTheba/memory-game/commit/47e3a5f07212e9a55fe6ad59ca85a1617b71fdad Clean up and sanitization
